site_name: Projectstartarchitectuur GBO
site_url: https://ictu.github.io/GBO-PSA/
repo_url: https://github.com/ICTU/GBO-PSA
repo_name: ictu/gbo

theme:
  name: material
  custom_dir: overrides
  language: nl
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - toc.follow

markdown_extensions:
  - tables
  - footnotes
  - sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - attr_list
  # Mermaid diagrammen
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.snippets:
      base_path:
        - docs
      check_paths: true
  # Automatische inhoudsopgave
  - toc:
      permalink: true
      toc_depth: 2

extra_css:
  - stylesheets/extra.css
  - stylesheets/pdf.css

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascript/mermaid-init.js
  - javascript/print.js

extra:
  version:
    provider: mike
    alias: true

plugins:
  - search
  - mike:
      canonical_version: "latest"
  - print-site:
      add_to_navigation: false
      print_page_title: "Documentatie GBO"
      enumerate_headings: false
      exclude:
        - index.md

nav:
  - GBO: https://ictu.github.io/GBO/latest/
  - Globaal Ontwerp: https://ictu.github.io/GBO-GO/latest/
  - Projectstartarchitectuur:
      - Inleiding: psa/inleiding.md
      - Oplossingsrichting: psa/oplossing.md
      - Architectuurprincipes: psa/architectuurprincipes.md
      - Ontwerpprincipes: psa/ontwerpprincipes.md
      - Ecosysteem en oplossingsrichting: psa/ecosysteem.md
      - Interactiepatronen: psa/interactiepatronen.md
      - Logische architectuur: psa/generieke-functies.md
      - Stelselfuncties: psa/capabilities.md
      - Realisatiestrategie: psa/realisatiestrategie.md
      - Open Vraagstukken en ontwerpkeuzes: psa/vraagstukken.md
  - Technisch Ontwerp: https://ictu.github.io/GBO-TO/latest/
  - Technische Requirements: https://ictu.github.io/GBO-TR/latest/
  - Semantiek: https://ictu.github.io/GBO-SEM/latest/
