flowchart LR

Bronhouder["Overheidsbron"]
DvTP["GBO
(afspraken, standaarden, voorzieningen)"]
Wallet["EUDI-Wallet"]
SDG["SDG/OOTS"]
Privaat["Private dienstverlener"]

Bronhouder --> DvTP
DvTP --> Wallet
DvTP --> SDG
DvTP --> Privaat
