flowchart LR
  subgraph gbo["GBO Basis"]
    direction TB
        fsc_pap("Beleidsregels")
        fsc("Standaard koppelvlak<br/>Generieke bronontsluiting<br/>Configurabele autorisatie")
        fsc_tools("GBO tools<br/>(ondersteuning bronhouders)")
  end
  subgraph eudi["EUDI-Wallet"]
    direction LR
        eudi_asi("Bronontsluiting voor QTSP<br/>(Authentic Source Interface)")
        eudi_pubeaa("Uitgifte van publieke EAA<br/>(PubEAA)")
        eudi_qeaa["QTSP<br/>(QEAA)"]
        eudi_wallet["EUDI-Wallet"]
  end
  subgraph oots["OOTS"]
    direction LR
        oots_adapter("OOTS adapter<br/>(protocol + semantische mapping)")
        oots_basis["Basisinrichting OOTS<br/>(nationaal OOTS-toegangspunt)"]
        oots_afnemer["Europese overheid<br/>SDG-portaal"]
  end
  subgraph dvtp["DvTP"]
    direction LR
        dvtp_toestemming("Toestemmingsvoorziening")
        dvtp_pseudoniem["Pseudonimiseervoorziening<br/>(BSNk PP)"]
        dvtp_afnemer["Private dienstverlener"]
  end

  fsc_pap --- fsc
  fsc --- fsc_tools
  bron[("Overheidsbronnen<br/>BRP · BD · UWV · KvK · …")] --- gbo
  eudi_asi --- eudi_qeaa
  eudi_qeaa --- eudi_wallet
  gbo --- eudi_asi & eudi_pubeaa & oots_adapter & dvtp_afnemer
  eudi_pubeaa --- eudi_wallet
  oots_adapter --- oots_basis
  oots_basis --- oots_afnemer
  gbo --- dvtp_toestemming
  dvtp_toestemming --- dvtp_afnemer
  dvtp_toestemming --- dvtp_pseudoniem
  dvtp_pseudoniem ~~~ dvtp_afnemer
  eudi_wallet --- burger["Burger"]
  oots_afnemer --- burger
  dvtp_afnemer --- burger

  fsc_pap:::gbo
  fsc:::gbo
  fsc_tools:::gbo
  eudi_asi:::gbo
  eudi_pubeaa:::gbo
  eudi_qeaa:::eudi
  eudi_wallet:::eudi
  oots_adapter:::gbo
  oots_basis:::oots
  oots_afnemer:::oots
  dvtp_toestemming:::gbo
  dvtp_pseudoniem:::dvtp
  dvtp_afnemer:::dvtp
  bron:::bron
  burger:::burger

  classDef bron fill:#edf7df,stroke:#6aa13a,color:#27500a
  classDef generiek fill:#f1efe8,stroke:#5f5e5a,color:#444441
  classDef eudi fill:#f1efe8,stroke:#5f5e5a,color:#444441
  classDef oots fill:#f1efe8,stroke:#5f5e5a,color:#444441
  classDef dvtp fill:#f1efe8,stroke:#5f5e5a,color:#444441
  classDef gbo fill:#fff0e8,stroke:#000000,color:#000000
  classDef burger fill:#edf7df,stroke:#6aa13a,color:#27500a
