```mermaid

flowchart LR

Bronhouder
DvTP["GBO stelsel
(afspraken, standaarden, voorzieningen)"]
Wallet
Privaat["Private partij"]
SDG["SDG/OOTS"]

Bronhouder --> DvTP
DvTP --> Wallet
DvTP --> Privaat
DvTP --> SDG

```
