``` mermaid

sequenceDiagram
participant PD as Private dienstverlener
participant AUTH as Autorisatiedienst
participant REG as Consentregister
participant INT as Integrator
participant BRON as Bronhouder

PD ->> AUTH: Gegevensverzoek + toestemmingstoken
AUTH ->> REG: Valideer toestemming
REG ->> AUTH: Toestemming geldig
AUTH ->> INT: Vraag gegevens op
INT ->> BRON: Gegevensverzoek
BRON ->> INT: Gegevens (met bronzegel)
INT ->> PD: Lever gegevens

```
