``` mermaid

sequenceDiagram
actor Burger
participant PD as Private dienstverlener
participant TI as Toegang & Interactie
participant ID as Identiteit & Vertrouwen
participant AUTH as Autorisatie

Burger ->> PD: Start dienst
PD ->> TI: Start toestemmingsflow
TI ->> ID: Authenticatieverzoek
ID ->> Burger: Vraag authenticatiemiddel
Burger ->> ID: Authenticatie
ID ->> TI: Identiteitsassertie
TI ->> AUTH: Controle toegangsregels
AUTH ->> TI: Toegang toegestaan
TI ->> PD: Authenticatie geslaagd

```
