``` mermaid

sequenceDiagram
actor Burger
participant PD as Private dienstverlener
participant TI as Toegang & Interactie
participant ID as Identiteit & Vertrouwen
participant CONSENT as Toestemmingsdienst
participant REG as Consentregister

Burger ->> PD: Start dienst
PD ->> TI: Initiatie toestemmingsflow
TI ->> ID: Authenticatie
ID ->> TI: Identiteit bevestigd
TI ->> CONSENT: Toon toestemmingsinformatie
CONSENT ->> Burger: Toon dataset / doel / partij
Burger ->> CONSENT: Geef toestemming
CONSENT ->> REG: Registreer toestemming
REG ->> CONSENT: Bevestiging
CONSENT ->> PD: Terugkoppeling resultaat

```
