flowchart LR
  subgraph gbo["GBO Basis"]
    direction TB
        gbo_pbac("Autorisatie<br/>(PBAC/FTV)")
        gbo_api("GraphQL<br/>(generiek)")
        gbo_fsc_in("FSC inway")
  end
  subgraph eudi["EUDI-Wallet"]
    direction LR
      eudi_fsc_out("FSC outway")
      eudi_asi("ASI-provider<br/>(verify dienst)")
      eudi_pubeaa("PubEAA-provider<br/>(PubEAA)")
      eudi_qeaa["QTSP<br/>(QEAA)"]
      eudi_wallet["EUDI-Wallet burger"]
  end
  subgraph oots["SDG / OOTS"]
    direction LR
      oots_fsc_out("FSC outway")
      oots_adapter("OOTS-V<br/>(GBO mapping)")
      oots_basis["eDelivery<br/>toegangspunt"]
      oots_afnemer["Europese overheid<br/>SDG-portaal"]
  end

%%  subgraph dvtp["DvTP"]
%%    direction LR
%%      dvtp_fsc_out("FSC outway")
%%      dvtp_toestemming("Toestemmingsvoorziening")
%%      dvtp_pseudoniem["Pseudonimiseervoorziening<br/>(BSNk PP)"]
%%      dvtp_afnemer["Private dienstverlener"]
%%  end

  bron[("Overheidsbronnen<br/>BRP · BD · UWV · KvK · …")] --- gbo_api --- gbo_pbac --- gbo_fsc_in
  gbo_fsc_in -- GraphQL --- eudi_fsc_out & oots_fsc_out
%%  gbo_fsc_in -- GraphQL --- dvtp_fsc_out
  eudi_fsc_out --- eudi_asi -- REST-JSON<br/>(HTTP / OAuth) --- eudi_qeaa -- OpenID4VCI --- eudi_wallet
  eudi_fsc_out --- eudi_pubeaa -- OpenID4VCI ---- eudi_wallet
  oots_fsc_out --- oots_adapter --- oots_basis -- eDelivery-AS4 --- oots_afnemer

%%  gbo_pbac -- REST-JSON<br/>(PIP) --- dvtp_toestemming
%%  dvtp_toestemming -- REST-JSON --- dvtp_afnemer
%%  dvtp_toestemming -- REST-JSON --- dvtp_pseudoniem
%%  dvtp_fsc_out --GraphQL--- dvtp_afnemer
%%  dvtp_fsc_out ~~~ dvtp_pseudoniem
%%  dvtp_fsc_out ~~~ oots_adapter
%%  dvtp_fsc_out ~~~ dvtp_toestemming
%%  oots_basis ~~~ dvtp_afnemer

  eudi_wallet --- burger["Burger"]
  oots_afnemer --- burger
%%  dvtp_afnemer --- burger

  gbo_fsc_in:::gbo
  gbo_api:::gbo
  gbo_pbac:::gbo
  eudi_fsc_out:::gbo
  eudi_asi:::gbo
  eudi_pubeaa:::gbo
  eudi_qeaa:::eudi
  eudi_wallet:::eudi
  oots_fsc_out:::gbo
  oots_adapter:::gbo
  oots_basis:::oots
  oots_afnemer:::oots

%%  dvtp_fsc_out:::gbo
%%  dvtp_toestemming:::gbo
%%  dvtp_pseudoniem:::dvtp
%%  dvtp_afnemer:::dvtp

  bron:::bron
  burger:::burger

  classDef bron fill:#edf7df,stroke:#6aa13a,color:#27500a
  classDef generiek fill:#f1efe8,stroke:#5f5e5a,color:#444441
  classDef eudi fill:#f1efe8,stroke:#5f5e5a,color:#444441
  classDef oots fill:#f1efe8,stroke:#5f5e5a,color:#444441
  classDef dvtp fill:#f1efe8,stroke:#5f5e5a,color:#444441
  classDef gbo fill:#fff0e8,stroke:#000000,color:#000000
  classDef burger fill:#edf7df,stroke:#6aa13a,color:#27500a
