flowchart LR
  subgraph gbo["Gemeenschappelijke Bronontsluiting (GBO)"]
    direction TB
        fsc_pap("Authorisatie<br>PBAC (FTV)")
        fsc("GraphQL-API<br/>(generiek)")
        fsc_inway("FSC<br/>Inway")
  end
  subgraph eudi["EUDI"]
    direction LR
        eudi_outway("FSC<br/>Outway")
        eudi_asi("ASI-provider<br/>(verify dienst)")
        eudi_pubeaa("PubEAA-provider<br/>(PubTSP)")
        eudi_qeaa("QEAA-provider<br/>(QTSP)")
        eudi_wallet("EUDI-Wallet")
  end
  subgraph oots["OOTS"]
    direction LR
        oots_outway("FSC<br/>Outway")
        oots_adapter("OOTS-V<br/>(GBO mapping)")
        oots_basis("eDelivery<br/>toegangspunt")
        oots_afnemer("Europese lidstaat<br/>SDG-portaal")
  end


  fsc ---fsc_pap---fsc_inway
  bron[("Overheidsbronnen<br/>(BRP, BD, UWV, KvK, gemeenten, etc.)")]  --- fsc
  eudi_asi -- REST-API<br/>(HTTP/OAuth) --- eudi_qeaa
  eudi_qeaa -- OpenID4VCI --- eudi_wallet
  fsc_inway -- GraphQL --- oots_outway & eudi_outway
  eudi_outway--- eudi_pubeaa -- OpenID4VCI ---- eudi_wallet
  eudi_outway--- eudi_asi
  oots_outway --- oots_adapter --- oots_basis
  oots_basis -- eDelivery/AS4 --- oots_afnemer

  eudi_wallet --- burger["Burger"]
  oots_afnemer --- burger


  fsc_pap:::gbo
  fsc:::gbo
  fsc_inway:::gbo
  eudi_asi:::gbo
  eudi_outway:::gbo
  eudi_pubeaa:::gbo
  eudi_qeaa:::eudi
  eudi_wallet:::eudi
  oots_adapter:::gbo
  oots_outway:::gbo
  oots_basis:::oots
  oots_afnemer:::oots
 
  bron:::bron
  burger:::burger

  classDef bron fill:#edf7df,stroke:#6aa13a,color:#27500a
  classDef generiek fill:#f1efe8,stroke:#5f5e5a,color:#444441
  classDef eudi fill:#efe0f5,stroke:#5f5e5a,color:#444441
  classDef oots fill:#efe0f5,stroke:#5f5e5a,color:#444441
  classDef dvtp fill:#f1efe8,stroke:#5f5e5a,color:#444441
  classDef gbo fill:#fff0e8,stroke:#000000,color:#000000
  classDef burger fill:#edf7df,stroke:#6aa13a,color:#27500a